### ISSUE TITLE
Blockers issues

### ISSUE THREAD

**Issue by Galixte** [imkingdavid/prefixed#11]
Hi,

are the blockers issues https://github.com/imkingdavid/prefixed/issues/3, https://github.com/imkingdavid/prefixed/issues/4, https://github.com/imkingdavid/prefixed/issues/6 & https://github.com/imkingdavid/prefixed/issues/7 prevents the use of this extension ?

**Comment by Galixte** [comment]
Hi @imkingdavid,

could you take a look ?

**Comment by imkingdavid** [comment]
The extension is currently unstable and should not be used in any sort of production/live environment. Those blockers are just the issues I've noticed and haven't had a chance to fix. There may be other issues as well.

**Comment by imkingdavid** [comment]
I've fixed most of the blockers.

Note that some of the blockers don't inhibit/prevent use and are just things that I am planning to add no matter what before a release, unless I change my mind.
