### ISSUE TITLE
Can't get it to work in 3.1.5

### ISSUE THREAD

**Issue by c0nnex** [imkingdavid/prefixed#12]
Extension installed, activated.
I can add Prefixes

But the Selection under the Subject will not appear :(

**Comment by rahlzel** [comment]
Confirmed on 3.1.5. Same problem.

Prosilver skin.
Using these other extensions: http://i.imgur.com/aEqk3Hf.png

**Comment by Galixte** [comment]
Hi @imkingdavid,

could you take a look ?

**Comment by imkingdavid** [comment]
Thanks for the bug report. I haven't tested this on 3.1.5 or 3.1.6 (will do soon, though). This extension is currently unstable and not ready for production/live use. I am planning to work on this as time permits but I cannot provide a timeline for release.

**Comment by imkingdavid** [comment]
Extension now works on 3.1.5+
